### ISSUE TITLE
Why should we even use this simple thing?

### ISSUE THREAD

**Issue by ghost** [sindresorhus/array-union#12]
Pretty sure the nodejs array basics has taught us this simple job...
`arr = [...new Set(arr.flat())]`
This is just a basic working of arrays on nodejs, so why should we use this?
The index.js file is literally so small, and also may I know are all these 6M people who use this never knew this simple thing?

**Comment by sindresorhus** [comment]
Look at the Git history and you'll see why it exists. It didn't used to be easy to do this.

**Comment by hayleyberryl2s** [comment]
projects that depend on packages like this are just begging for a security breach
